// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cis_proj.Models;

#nullable disable

namespace cis_proj.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260828005143_SeedStaffUsers")]
    partial class SeedStaffUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cis_proj.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A refreshing cocktail made with rum, lime juice, sugar, mint leaves, and soda water.",
                            Name = "Mojito",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A classic cocktail made with tequila, lime juice, and orange liqueur, served in a salt-rimmed glass.",
                            Name = "Margarita",
                            Price = 9.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A timeless cocktail made with bourbon or rye whiskey, sugar, bitters, and a twist of citrus.",
                            Name = "Old Fashioned",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "A stylish cocktail made with vodka, triple sec, cranberry juice, and lime juice.",
                            Name = "Cosmopolitan",
                            Price = 9.50m
                        });
                });

            modelBuilder.Entity("cis_proj.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedBartenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrinkId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBartenderId");

                    b.HasIndex("DrinkId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("cis_proj.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "bartender@bar.com",
                            Name = "Sam Barkeep",
                            Password = "4523f961e3845992b04ae19a48d846a986d87062e5c9e91c785b4c691dbd4636",
                            Role = "Bartender"
                        },
                        new
                        {
                            Id = 2,
                            Email = "server@bar.com",
                            Name = "Riley Server",
                            Password = "14bf075c90460abf992eded5e80766dc474229ecc33a72b63e6844cce4a5f32c",
                            Role = "Server"
                        });
                });

            modelBuilder.Entity("cis_proj.Models.Order", b =>
                {
                    b.HasOne("cis_proj.Models.User", "AssignedBartender")
                        .WithMany()
                        .HasForeignKey("AssignedBartenderId");

                    b.HasOne("cis_proj.Models.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBartender");

                    b.Navigation("Drink");
                });
#pragma warning restore 612, 618
        }
    }
}
